services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_INTERNAL_URL: ${API_INTERNAL_URL:-http://localhost:8347}
    restart: unless-stopped
    ports:
      - "4821:4821"
    environment:
      - NODE_ENV=production
